//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buyer> buyers { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<leftover> leftovers { get; set; }
        public virtual DbSet<postoffice> postoffices { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<request_rows> request_rows { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<pay> pays { get; set; }
    }
}
