//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_rows
    {
        public int id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string name { get; set; }
        public string ed_izm { get; set; }
        public Nullable<int> goods_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string code { get; set; }
        public Nullable<decimal> fact_amount { get; set; }
        public string partner { get; set; }
    
        public virtual good good { get; set; }
        public virtual request request { get; set; }
    }
}
