//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_rows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_rows()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string name { get; set; }
        public string ed_izm { get; set; }
        public Nullable<int> goods_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string barcode { get; set; }
        public decimal paid_amount { get; set; }
        public decimal return_amount { get; set; }
    
        public virtual request request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
    }
}
