//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request()
        {
            this.request_rows = new HashSet<request_rows>();
            this.pays = new HashSet<pay>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string username { get; set; }
        public Nullable<int> category { get; set; }
        public string comment { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual buyer buyer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_rows> request_rows { get; set; }
        public virtual state state { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pay> pays { get; set; }
    }
}
